'use strict';

gymManagementApp.controller('searchMemberController', function ($scope, $state, $http, $rootScope, $location, Idle, $route, exDialog, commonService, $localStorage, userSessionService) {

    $scope.init = function ()
    {
        Idle.watch();
        $location.path('/dashboard/searchMember');
        $scope.test1 = 'This Is About us Page';

        $scope.searchMember = [
                           { Enquiry_id: 1, Member_id: 1, photourl: '/Images/PlanetImages/PlanetLogo/Planet Fitness Gym Logo.png', fname: 'sham', mname: 'ashok', Lname: 'patil', mobile: '9763636866', Email: 'patilsham007@gmail.com', Packages: 'platinum', Services: 'fitness, swimming,Zumba', Admission_Date: '14-April-2016', Address: 'At Post: Savde', City: 'Bhadgaon', State: 'Maharashtra', Pin_Code: '425112', Package_Expire: '13-April-2017', Marrital_Status: 'Unmarried', Gender: 'Male', MembershipStatus: 'Active' },
                           { Enquiry_id: 2, Member_id: 2,photourl: '/Images/PlanetImages/PlanetLogo/Planet Fitness Gym Logo.png', fname: 'ghanshyam', mname: 'shantaram', Lname: 'patil', mobile: '8527419630', Email: 'ghanshyampatil1989@gmail.com', Packages: 'Gold', Services: 'fitness, swimming,Zumba', Admission_Date: '14-April-2016', Address: 'At Post: Savde', City: 'Bhadgaon', State: 'Maharashtra', Pin_Code: '425112', Package_Expire: '13-April-2017', Marrital_Status: 'Unmarried', Gender: 'Male', MembershipStatus: 'Active' },
                           { Enquiry_id: 3, Member_id: 3,photourl: '/Images/PlanetImages/PlanetLogo/Planet Fitness Gym Logo.png', fname: 'sidharth', mname: '', Lname: 'kamble', mobile: '9763636866', Email: 'sidkamble@gmail.com', Packages: 'silver', Services: 'fitness', Admission_Date: '14-April-2016', Address: 'At Post: Savde', City: 'Bhadgaon', State: 'Maharashtra', Pin_Code: '425112', Package_Expire: '13-April-2017', Marrital_Status: 'Unmarried', Gender: 'Male', MembershipStatus: 'Active' },
                           { Enquiry_id: 4, Member_id: 4,photourl: '/Images/PlanetImages/PlanetLogo/Planet Fitness Gym Logo.png', fname: 'vishal', mname: '', Lname: 'patil', mobile: '9763636866', Email: 'vishalpatil@gmail.com', Packages: 'Silver', Services: 'swimming', Admission_Date: '14-April-2016', Address: 'At Post: Savde', City: 'Bhadgaon', State: 'Maharashtra', Pin_Code: '425112', Package_Expire: '13-April-2017', Marrital_Status: 'Unmarried', Gender: 'Male', MembershipStatus: 'Active' },
                           { Enquiry_id: 5, Member_id: 5,photourl: '/Images/PlanetImages/PlanetLogo/Planet Fitness Gym Logo.png', fname: 'Ashwini', mname: '', Lname: 'Dhamne', mobile: '7412589630', Email: 'ashwinid@gmail.com', Packages: 'platinum', Services: 'Zumba', Admission_Date: '14-April-2016', Address: 'At Post: Savde', City: 'Bhadgaon', State: 'Maharashtra', Pin_Code: '425112', Package_Expire: '13-April-2017', Marrital_Status: 'Unmarried', Gender: 'Male', MembershipStatus: 'Active' },
                           { Enquiry_id: 6, Member_id: 6,photourl: '/Images/PlanetImages/PlanetLogo/Planet Fitness Gym Logo.png', fname: 'swapnil', mname: 'ashok', Lname: 'patil', mobile: '9763636866', Email: 'swapnilapatil@gmail.com', Packages: 'platinum', Services: 'fitness, swimming,Zumba', Admission_Date: '14-April-2016', Address: 'At Post: Savde', City: 'Bhadgaon', State: 'Maharashtra', Pin_Code: '425112', Package_Expire: '13-April-2017', Marrital_Status: 'Unmarried', Gender: 'Male', MembershipStatus: 'Active' },
                           { Enquiry_id: 7, Member_id: 7,photourl: '/Images/PlanetImages/PlanetLogo/Planet Fitness Gym Logo.png', fname: 'manoj', mname: 'Digamber', Lname: 'jadhav', mobile: '9763636866', Email: 'manojdjadhav@gmail.com', Packages: 'platinum', Services: 'swimming,Zumba', Admission_Date: '14-April-2016', Address: 'At Post: Savde', City: 'Bhadgaon', State: 'Maharashtra', Pin_Code: '425112', Package_Expire: '13-April-2017', Marrital_Status: 'Unmarried', Gender: 'Male', MembershipStatus: 'Active' },
                           { Enquiry_id: 8, Member_id: 8,photourl: '/Images/PlanetImages/PlanetLogo/Planet Fitness Gym Logo.png', fname: 'sushil', mname: 'chagan', Lname: 'patil', mobile: '9763636866', Email: 'sushcpatil@gmail.com', Packages: 'platinum', Services: 'fitness, swimming', Admission_Date: '14-April-2016', Address: 'At Post: Savde', City: 'Bhadgaon', State: 'Maharashtra', Pin_Code: '425112', Package_Expire: '13-April-2017', Marrital_Status: 'Unmarried', Gender: 'Male', MembershipStatus: 'Active' },
                           { Enquiry_id: 9, Member_id: 8,photourl: '/Images/PlanetImages/PlanetLogo/Planet Fitness Gym Logo.png', fname: 'vivek', mname: 'Ramesh', Lname: 'mali', mobile: '9763636866', Email: 'vivekrmali@gmail.com', Packages: 'silver', Services: 'fitness, swimming,Zumba', Admission_Date: '14-April-2016', Address: 'At Post: Savde', City: 'Bhadgaon', State: 'Maharashtra', Pin_Code: '425112', Package_Expire: '13-April-2017', Marrital_Status: 'Unmarried', Gender: 'Male', MembershipStatus: 'Active' },
                           { Enquiry_id: 10, Member_id: 10,photourl: '/Images/PlanetImages/PlanetLogo/Planet Fitness Gym Logo.png', fname: 'kiran', mname: 'ashok', Lname: 'chaudhari', mobile: '9763636866', Email: 'kiranchau@gmail.com', Packages: 'silver', Services: 'fitness, swimming,Zumba', Admission_Date: '14-April-2016', Address: 'At Post: Savde', City: 'Bhadgaon', State: 'Maharashtra', Pin_Code: '425112', Package_Expire: '13-April-2017', Marrital_Status: 'Unmarried', Gender: 'Male', MembershipStatus: 'Active' }
        ];
        $scope.members = { data: 'searchMember' }
    };
    $scope.init();
});
